language: ruby
rvm:
  - 2.1.1

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role naopassarao SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database naopassarao_test;' -U naopassarao postgres"
  - "sh -e /etc/init.d/xvfb start"

env:
  - DISPLAY=:99.0

script:
  - "CODECLIMATE_REPO_TOKEN=230c18c8de99e52184928304c7773b3db571d0f9b4c50ffbb7d9975c671bd2b2 bundle exec rspec spec"
  - "CODECLIMATE_REPO_TOKEN=230c18c8de99e52184928304c7773b3db571d0f9b4c50ffbb7d9975c671bd2b2 bundle exec cucumber"

branches:
  only:
    - master
